version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config:ro
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
